server:
  context-path: /training

spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

open:
  api:
    title: API Documents
    version: v1.0.0
    description: APIs docs for Training Exercise
    serverUrl: http://localhost:8080
    serverDescription: local
